# Setup
setup: pretext

# Model
backbone: resnet_ts
model_kwargs:
  head: mlp
  features_dim: 3
res_kwargs:
  in_channels: 38
  mid_channels: 4

# Dataset
train_db_name: smd
val_db_name: smd
preload_aug: False
window_size: 200
window_stride: 5
num_classes: 10

# Loss
criterion: pretext
criterion_kwargs:
  temperature: 0.4

# Hyperparameters
epochs: 30
optimizer: adam
optimizer_kwargs:
  #nesterov: False
  #momentum: 0.9
  lr: 0.001
  weight_decay: 0
scheduler: cosine
scheduler_kwargs:
  lr_decay_rate: 0.01
batch_size: 512
num_workers: 16

# Transformations
augmentation_strategy: ts
transformation_kwargs:
  noise_sigma: 0.01

anomaly_kwargs:
  portion: 0.99