# Setup
setup: pretext

# Model
backbone: resnet_ts
model_kwargs:
  head: mlp
  features_dim: 4
res_kwargs:
  in_channels: 38
  mid_channels: [38, 38]

# Dataset
train_db_name: smd
val_db_name: smd
preload_aug: True
window_size: 200
window_stride: 5
num_classes: 10

# Loss
criterion: pretext
criterion_kwargs:
  temperature: 0.4
  pos_weight: 1
  neg_weight: 1.5

# Hyperparameters
epochs: 10000
optimizer: sgd
optimizer_kwargs:
  #nesterov: False
  #momentum: 0.9
  lr: 0.01
  weight_decay: 0
scheduler: cosine_restart
scheduler_kwargs:
  lr_warmup_epochs: 20
  lr_eta_min: 0.000000001
  T_period: 50
  T_mul: 2
  lr_decay_epochs: [10, 20]
  lr_decay_rate: 0.01
batch_size: 50
num_workers: 0

# Transformations
augmentation_strategy: ts
transformation_kwargs:
  noise_sigma: 0.01

anomaly_kwargs:
  portion: 0.99