# setup
setup: classification

# Loss
criterion: classification
criterion_kwargs:
   entropy_weight: 5

# Weight update
update_cluster_head_only: False # Update full network in classification
num_heads: 1 # Only use one head

# Model
backbone: resnet_ts

# Dataset
train_db_name: Power
val_db_name: Power
ds_name: '152_UCR_Anomaly_PowerDemand1_9000_18485_18821.txt'
num_classes: 6
num_neighbors: 3

# Transformations
augmentation_strategy: ts
transformation_kwargs:
   noise_sigma: 0.01

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.01
   weight_decay: 0.001
epochs: 50
batch_size: 100
num_workers: 1

# Scheduler
scheduler: constant

anomaly_kwargs:
   portion: 0.99