# setup
setup: classification

# Loss
criterion: classification
criterion_kwargs:
   entropy_weight: 5
   consistency_weight: 1
   inconsistency_weight: 1

# Weight update
update_cluster_head_only: False # Update full network in classification
num_heads: 1 # Only use one head

# Model
backbone: resnet_ts
res_kwargs:
  in_channels: 38
  mid_channels: [38, 38]
amp: False # Not working for now

# Dataset
train_db_name: smd
val_db_name: smd
preload_aug: True
window_size: 200
window_stride: 5
num_classes: 10
num_neighbors: 5

# Transformations
augmentation_strategy: ts
transformation_kwargs:
   noise_sigma: 0.01

# Hyperparameters
epochs: 2000
optimizer: adam
optimizer_kwargs:
  #nesterov: False
  #momentum: 0.9
  lr: 0.0005
  weight_decay: 0.001

# Scheduler
scheduler: cosine_restart
scheduler_kwargs:
  lr_warmup_epochs: 20
  lr_eta_min: 0.000000001
  T_period: 50
  T_mul: 2
  lr_decay_epochs: [10, 20]
  lr_decay_rate: 0.01
batch_size: 50
num_workers: 0

anomaly_kwargs:
   portion: 0.99