# Setup
setup: pretext

# Model
backbone: resnet_ts
model_kwargs:
  head: mlp
  features_dim: 4
res_kwargs:
  in_channels: 38
  mid_channels: [4, 8]
  kernel_sizes: [8, 5, 3]
  norm_layer_name: batch
  window_size: 256
  dropout: True

# Dataset
train_db_name: smd
val_db_name: smd
wsz: 256 #200
stride: 5
num_classes: 10

# Loss
criterion: pretext
criterion_kwargs:
  temperature: 0.4
  loss_name: euclidean
  device: cuda
  normalize: True
  clamp_neg_loss: False
  crop: False
  crop_size_min: 5
  crop_size_max: 10
  pos_weight: 1
  neg_weight: 1
  initial_margin: 1.0
  max_margin: 5.0
  min_margin: 0.01
  margin_distance: False
  adjust_factor: 0
  ema_alpha: 0
  ema_distance: False
  pos_supression: False
  re_weight: False

# Hyperparameters
epochs: 2000
optimizer: adamw
optimizer_kwargs:
  lr: 0.001
  weight_decay: 0.0005
# Scheduler
scheduler: cosine_restart
scheduler_kwargs:
  lr_warmup_epochs: 100 #20 #100
  lr_eta_min: 0.0005
  T_period: 500 #50 #1500
  T_mul: 1
  lr_decay_epochs: [10, 20]
  lr_decay_rate: 0.01
batch_size: 512
num_workers: 0

# Transformations
augmentation_strategy: ts
transformation_kwargs:
  noise_sigma: 0.01

anomaly_kwargs:
  portion: 0.99